// Generated by CoffeeScript 1.6.3
(function() {
  describe("Gauge View Model", function() {
    it("should start with current time", function() {
      spyOn(GaugeViewModel.prototype, 'getDate').andReturn(new Date(2014, 1, 1, 11, 22, 33));
      this.vm = new GaugeViewModel();
      expect(this.vm.hour()).toBe(11);
      expect(this.vm.minute()).toBe(22);
      return expect(this.vm.second()).toBe(33);
    });
    return it("should set observables when update called", function() {
      this.vm = new GaugeViewModel();
      spyOn(this.vm, 'getDate').andReturn(new Date(2014, 1, 1, 16, 17, 18));
      this.vm.update();
      expect(this.vm.hour()).toBe(16);
      expect(this.vm.minute()).toBe(17);
      return expect(this.vm.second()).toBe(18);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=gaugeViewModelSpec.map
*/
